### ISSUE TITLE
AI generated names

### ISSUE THREAD

**Issue by JaxTurboNerd** [Pets-without-names/Jax-Pet-Names#19]
Use Openai or another ai source to allow the user to use AI chat to generate names or a list of names.  This will also allow the user to add some creativity such as cartoon or movie character themes.  I created a local branch and have this functionality working through my Openai account.  let me know if anyone is interested.

**Comment by murjax** [comment]
Any interest in this still? OpenAI appears to charge for their base GPT 3.5 model currently. Not sure if that's something we want to open up. Alternatively we could let users import names (from ChatGPT or elsewhere) with a bulk import tool.

**Comment by JaxTurboNerd** [comment]
I was aware of the cost using Chat GPT when I created this issue.  I am still interested but not committed to adding this functionality.  I'm definitely open to ideas as you mentioned.

**Comment by JaxTurboNerd** [comment]
OpenAI Information: https://platform.openai.com/docs/guides/prompt-engineering

**Comment by JaxTurboNerd** [comment]
created branch 'openai'
